export const analysisMapping: Record<string, string> = {
    "NOUN:MS": "Noun (Masc. Sing.)",
    "NOUN:FS": "Noun (Fem. Sing.)",
    "NOUN:P": "Noun (Plural)",
    "NOUN:PHRASE": "Noun Phrase",
    "INTERJ": "Interjection",
    "VERB_PSEUDO": "Pseudo-Verb",
    "ADJ:MS": "Adjective (Masc. Sing.)",
    "VERB:C": "Verb (Completed/Past)",
    "VERB:I": "Verb (Incomplete/Present)",
    "VERB:P": "Verb (Plural)", // Assuming P is plural, though usually I/C covers tense
    "NOUN_ACT:MS": "Active Participle (Masc. Sing.)",
    "NOUN_PASS": "Passive Participle",
    "PRON:1P": "Pronoun (1st Person Plural)",
    "VERB:PHRASE": "Verb Phrase",
    "NOUN_PASS:PHRASE": "Passive Participle Phrase",
    "NOUN_ACT:PHRASE": "Active Participle Phrase",
    "ADJ_NUM": "Numeral Adjective",
    "ADJ:P": "Adjective (Plural)",
    "ADV": "Adverb",
    "ADV:PHRASE": "Adverbial Phrase",
    "ADJ:PHRASE": "Adjective Phrase",
    "ADJ_NUM:PHRASE": "Numeral Phrase",
    "VERB_NOM": "Verbal Noun",
    "VERB_NOM:PHRASE": "Verbal Noun Phrase",
    "NOUN:FP": "Noun (Fem. Plural)",
    "NOUN_PROP": "Proper Noun",
    "NOUN_PROP:PHRASE": "Proper Noun Phrase",
    "CONJ_SUB": "Subordinating Conjunction",
    "CONJ": "Conjunction",
    "CONJ:PHRASE": "Conjunction Phrase",
    "INTERJ:PHRASE": "Interjection Phrase",
    "PART_DET": "Particle (Determiner)",
    "ABBREV": "Abbreviation",
    "ABBREV:PHRASE": "Abbreviation Phrase",
    "ADJ/NOUN": "Adjective/Noun",
    "NOUN_NUM": "Number",
    "NOUN_NUM:P": "Number (Plural)",
    "NOUN_NUM:PHRASE": "Number Phrase",
    "PART_RESTRICT": "Particle (Restrictive)",
    "PRON_REL": "Relative Pronoun",
    "PART_FOCUS": "Particle (Focus)",
    "PRON:1S": "Pronoun (1st Person Sing.)",
    "PRON:2MS": "Pronoun (2nd Person Masc. Sing.)",
    "PRON:2FS": "Pronoun (2nd Person Fem. Sing.)",
    "PRON:2P": "Pronoun (2nd Person Plural)",
    "PRON:2FP": "Pronoun (2nd Person Fem. Plural)",
    "VERB_PSEUDO:PHRASE": "Pseudo-Verb Phrase",
    "PRON_INTERROG": "Interrogative Pronoun",
    "NOUN": "Noun",
    "ADJ_NUM:P": "Numeral Adjective (Plural)",
    "ADJ_NUM:S": "Numeral Adjective (Sing.)",
    "PRON_INTERROG:PHRASE": "Interrogative Pronoun Phrase",
    "ADV_INTERROG": "Interrogative Adverb",
    "ADV_REL": "Relative Adverb",
    "NOUN_QUANT": "Quantifier",
    "PREP": "Preposition",
    "ADJ:FS": "Adjective (Fem. Sing.)",
    "ADJ_COMP": "Comparative Adjective",
    "ADJ_COMP:PHRASE": "Comparative Adjective Phrase",
    "NOUN_QUANT:MS": "Quantifier (Masc. Sing.)",
    "NOUN_QUANT:PHRASE": "Quantifier Phrase",
    "PART_NEG": "Negative Particle",
    "NOUN:PL": "Noun (Plural)",
    "CONJ_SUB:PHRASE": "Subordinating Conjunction Phrase",
    "ADJ/NOUN:PHRASE": "Adjective/Noun Phrase",
    "NOUN_ACT": "Active Participle",
    "NOUN_QUANT:FS": "Quantifier (Fem. Sing.)",
    "NOUN:SF": "Noun (Sing. Fem.)", // Assuming SF is Sing Fem
    "NOUN:MP": "Noun (Masc. Plural)",
    "PRON_DEM:MS": "Demonstrative Pronoun (Masc. Sing.)",
    "PRON_DEM:PHRASE": "Demonstrative Pronoun Phrase",
    "NOUN_QUANT:P": "Quantifier (Plural)",
    "PART_FUT": "Future Particle",
    "PART_INTERROG": "Interrogative Particle",
    "PART": "Particle",
    "NOUN_ACT:P": "Active Participle (Plural)",
    "PREP:PHRASE": "Preposition Phrase",
    "PART_PROG:PHRASE": "Progressive Particle Phrase",
    "PART_PROG": "Progressive Particle",
    "NOUN:D": "Noun (Dual)",
    "ADJ": "Adjective",
    "PART_NEG:PHRASE": "Negative Particle Phrase",
    "ADV_INTERROG:PHRASE": "Interrogative Adverb Phrase",
    "PRON_EXCLAM": "Exclamatory Pronoun",
    "PRON_EXCLAM:PHRASE": "Exclamatory Pronoun Phrase",
    "NOUN_PASS:MS": "Passive Participle (Masc. Sing.)",
    "NOUN_NUM:S": "Number (Sing.)",
    "PRON_DEM:FS": "Demonstrative Pronoun (Fem. Sing.)",
    "PRON_DEM:P": "Demonstrative Pronoun (Plural)",
    "PRON_DEM:MP": "Demonstrative Pronoun (Masc. Plural)",
    "PRON_DEM:FP": "Demonstrative Pronoun (Fem. Plural)",
    "PRON:P": "Pronoun (Plural)",
    "PRON:FP": "Pronoun (Fem. Plural)",
    "PRON:MS": "Pronoun (Masc. Sing.)",
    "PRON:FS": "Pronoun (Fem. Sing.)",
    "PRON_DEM:3MS": "Demonstrative Pronoun (3rd Masc. Sing.)",
    "PRON_DEM:1S": "Demonstrative Pronoun (1st Sing.)",
    "PRON_DEM:3FS": "Demonstrative Pronoun (3rd Fem. Sing.)",
    "PRON_DEM:3P": "Demonstrative Pronoun (3rd Plural)",
    "PRON_DEM:3FP": "Demonstrative Pronoun (3rd Fem. Plural)",
    "PART_VOC": "Vocative Particle"
};

export function getReadableAnalysis(analysis?: string): string {
    if (!analysis) return '';
    return analysisMapping[analysis] || analysis;
}
